version: '3.7'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master communication port for Spark workers
      - "4040:4040"  # For Spark context viewing DAG
    volumes:
      - /workspaces/WeatherDataAnalysisUsingSpark/data/:/workspaces/WeatherDataAnalysisUsingSpark/data/  # Shared data volume for the cluster
      - /workspaces/WeatherDataAnalysisUsingSpark/notebooks/:/workspaces/WeatherDataAnalysisUsingSpark/notebooks/
    restart: unless-stopped

  spark-worker1:
    image: bitnami/spark:latest
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    ports:
      - "8081:8081"
    volumes:
      - /workspaces/WeatherDataAnalysisUsingSpark/data/:/workspaces/WeatherDataAnalysisUsingSpark/data/  # Ensure same mount point as master
      - /workspaces/WeatherDataAnalysisUsingSpark/notebooks/:/workspaces/WeatherDataAnalysisUsingSpark/notebooks/
    depends_on:
      - spark-master
    restart: unless-stopped

  spark-worker2:
    image: bitnami/spark:latest
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    ports:
      - "8082:8081"
    volumes:
      - /workspaces/WeatherDataAnalysisUsingSpark/data/:/workspaces/WeatherDataAnalysisUsingSpark/data/  # Ensure same mount point as master
      - /workspaces/WeatherDataAnalysisUsingSpark/notebooks/:/workspaces/WeatherDataAnalysisUsingSpark/notebooks/
    depends_on:
      - spark-master
    restart: unless-stopped

  spark-worker3:
    image: bitnami/spark:latest
    container_name: spark-worker3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    ports:
      - "8083:8081"
    volumes:
      - /workspaces/WeatherDataAnalysisUsingSpark/data/:/workspaces/WeatherDataAnalysisUsingSpark/data/  # Ensure same mount point as master
      - /workspaces/WeatherDataAnalysisUsingSpark/notebooks/:/workspaces/WeatherDataAnalysisUsingSpark/notebooks/
    depends_on:
      - spark-master
    restart: unless-stopped

  # zeppelin:
  #   image: apache/zeppelin:0.9.0
  #   container_name: zeppelin
  #   ports:
  #     - "8890:8080"
  #   environment:
  #     - ZEPPELIN_LOG_DIR=/logs
  #     - ZEPPELIN_NOTEBOOK_DIR=/notebook
  #   volumes:
  #     - ./data:/data  # Separate volume for Zeppelin
  #     - ./notebooks:/notebooks
  #   depends_on:
  #     - spark-master
  #   restart: unless-stopped

volumes:
  data:
    driver: local
  zeppelin-data:
    driver: local
